# Generated by Django 3.2.7 on 2023-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
