# Generated by Django 3.2.7 on 2023-05-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasApp', '0002_reservacion_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='ReservasApp/static/img'),
        ),
    ]
