# Generated by Django 3.2.7 on 2023-06-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasApp', '0003_alter_reservacion_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='hora_finalizacion',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='nombre',
        ),
    ]
